version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    build: ./house-api
    command: mix phx.server
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    volumes:
      - ./house-api:/app

  web:
    build: ./house-gui
    command: npm start -- -H 0.0.0.0
    volumes:
      - ./house-gui:/app

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
